"use client"
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "react-redux";
import { Store } from "@reduxjs/toolkit";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ThanhMenu from "./components/ThanhMenu";
import { store } from "./lib/store";




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="vi">
        <body>
            <div className="w-7/8 m-auto text-[1.2em]">
              <header className="h-[120px] relative "> <Header></Header> </header>
              <nav className="bg-lime-500 h-[60px]"> <ThanhMenu></ThanhMenu> </nav>
              <main className="min-h-[300px]  bg-emerald-100"> {children} </main>
              <footer className="bg-stone-950 text-white text-center p-[10px]">
                <Footer></Footer>
              </footer>
            </div>
        </body>
      </html>
    </Provider>
  );
}
